<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZWKWAbp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZWKWAbp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZWKWAbp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZWKWAbp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZWKWAbp\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZWKWAbp',
    'container.build_id' => 'b86d9c3f',
    'container.build_time' => 1658478626,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZWKWAbp');
