<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMBoA1HE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMBoA1HE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMBoA1HE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMBoA1HE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMBoA1HE\App_KernelDevDebugContainer([
    'container.build_hash' => 'MBoA1HE',
    'container.build_id' => 'f54ab514',
    'container.build_time' => 1658476620,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMBoA1HE');
